import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)

  let res = cookies().get('mode')
  return (
    <html lang="en">
      <body className={ res != undefined && res.value == 'dark' ? "dark-mode" : ''}>
        <div className="navbar">
          <Link href="/" className="logo">민성제 Forum</Link>
          <Link href="/list">List</Link>
          {
            session ?
              <span>어서와요, {session.user.name} <LogoutBtn></LogoutBtn></span> 
              :
              <LoginBtn></LoginBtn>
          }
          <DarkMode/>
        </div>
        {children}
      </body>
    </html>
  );
}
